#!/bin/bash

mkdir -p ~/github
cd ~/github 
rm -rf linux
git clone https://github.com/spacenoxxx/linux.git
cd ~/github/linux 
cp ~/.bashrc ~/.bashrc_default 
cat chaitanya-bashrc > ~/.bashrc 
cd tmp 
sudo apt install curl -y
curl -sS https://starship.rs/install.sh | sh 
cat starship.toml > ~/.config/starship.toml
mkdir -p ~/.local/share/fonts 
cd ~/.local/share/fonts 
wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/CascadiaCode.zip 
unzip CascadiaCode.zip  
rm CascadiaCode.zip 
rm readme.md 
rm LICENSE 
fc-cache ~/.local/share/fonts
source ~/.bashrc

##XRDP
cd /tmp && wget https://www.c-nergy.be/downloads/xRDP/xrdp-installer-1.4.6.zip
unzip xrdp-installer-1.4.6.zip 
chmod +x  ./xrdp-installer-1.4.6.sh
./xrdp-installer-1.4.6.sh -s -l
sudo reboot

